### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ThomasCFelix** [Nexuzzzz/Cerberus#5]
python3 main.py

 - Error, failed to import core modules.
 - Stacktrace:

Traceback (most recent call last):
  File "/root/Cerberus/main.py", line 64, in <module>
    from src.utils import * # import all utilities
  File "/root/Cerberus/src/utils.py", line 79, in <module>
    class utils():
  File "/root/Cerberus/src/utils.py", line 385, in utils
    def make_json_payload(self, indent: int | None = randint(1, 4)) -> tuple:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by Nexuzzzz** [comment]
What version are you using?

**Comment by Nexuzzzz** [comment]
Ahh i found out why its causing errors, `|` in function arguments was introduced in Python 3.10, and the recommended version is still 3.9 so it will cause errors. I'll bump the version to 3.10 and update the code aswell. Thank you for notifying me
